apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: default
  annotations:
    "eks.amazonaws.com/compute-type": "ec2"
    "eks.amazonaws.com/cloudwatch-log-group": "/aws/eks/{{ .Values.clusterName }}/frontend"
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "80"
    spec:
      containers:
      - name: frontend
        image: {{ .Values.frontend.image }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
          name: http
        
        # Add resources section for better monitoring
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
            
        # Add readiness and liveness probes
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 3
            
        env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: AWS_REGION
            value: {{ .Values.region | default "eu-central-1" }}
          - name: LOG_GROUP_NAME
            value: "/aws/eks/{{ .Values.clusterName }}/frontend"
