apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
  namespace: kube-system
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: external-dns
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: external-dns
    spec:
      serviceAccountName: external-dns
      containers:
      - name: external-dns
        image: registry.k8s.io/external-dns/external-dns:v{{ .Values.version }}
        args:
        - --source=ingress
        - --domain-filter={{ .Values.domainFilter }}
        - --provider=aws
        - --aws-zone-type=public
        - --registry=txt
        - --txt-owner-id={{ .Values.txtOwnerId }}
        - --policy=sync
        env:
        - name: AWS_REGION
          value: {{ .Values.region }}