apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: default
type: Opaque
data:
  DB_USER: {{ .Values.secrets.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.secrets.dbPassword | b64enc | quote }}
  DB_URL: {{ .Values.secrets.dbUrl | b64enc | quote }}