name: Deploy Infrastructure via Terraform

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform -chdir=terraform init


      - name: Terraform Plan Test
        id: plan
        run: terraform -chdir=terraform plan -var-file=apply-tfvars/prod.tfvars

      - name: Terraform Apply
        if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
        run: terraform -chdir=terraform apply -auto-approve -var-file=apply-tfvars/prod.tfvars

      - name: Comment PR with Plan
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ### Terraform Plan (prod.tfvars)
            ```
            ${{ steps.plan.outputs.stdout }}
            ```
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          AWS_DEFAULT_REGION: eu-central-1
          AWS_REGION: eu-central-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
